# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:11.14

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - install_dependencies
  - build
  - test
  - deploy

install_dependencies:
  stage: install_dependencies
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - npm ci
  only:
    changes:
      - package-lock.json

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - dist/
  script:
    - npm run build
  only:
    - develop
    - master
    - tags

unit-test:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - reports/
    reports:
      junit: junit.xml
  script:
    - npm test

lint:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm run lint:check

format:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm run format:check

publish:
  stage: deploy
  environment:
    name: publish
    url: https://npmjs.com/package/rev-service
  only:
    - tags
  except:
    - branches
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - dist/
    policy: pull
  dependencies:
    - build
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish

pages:
  stage: deploy
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - reports/
    policy: pull
  dependencies:
    - unit-test
  script:
    - mkdir -p public/reports/$CI_COMMIT_REF_NAME/coverage/
    - mkdir -p public/reports/$CI_COMMIT_REF_NAME/test/
    - mv reports/coverage/lcov-report/* public/reports/$CI_COMMIT_REF_NAME/coverage/
    - mv reports/test/* public/reports/$CI_COMMIT_REF_NAME/test/
  artifacts:
    paths:
      - public
    expire_in: 30 days